server:
  port: ${PORT:8082}

spring:
  application:
    name: ms-prestamos

  datasource:
    username: ${DATABASE_USER:admin}
    password: ${DATABASE_PASSWORD:Admin.123}
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mariadb://localhost:3306/prestamos_db}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  jackson:
    property-naming-strategy: SNAKE_CASE

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  app:
    name: MS-PRESTAMOS
    description: Microservicio para la gestión de prestamos de libros

springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: ms-prestamos

service:
  libros:
    url: http://ms-libros/api/libros/%s
